import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import "@n8n/chat/style.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        
        <Script
          id="n8n-chat-widget"
          strategy="afterInteractive"
          src="https://cdn.jsdelivr.net/npm/@n8n/chat/dist/chat.bundle.es.js"
          type="module"
          onLoad={() => {
            // Declaramos Chat como 'any' para evitar el error de tipos de TypeScript
            const n8nChat = (window as any).Chat;
            
            if (n8nChat) {
              n8nChat.createChat({
                webhookUrl: 'https://marcelomena.app.n8n.cloud/webhook/183180e2-0bfe-41a9-b48c-faac017ed657/chat',
                showWelcomeScreen: true,
                title: 'Asistente IA',
                i18n: {
                  en: {
                    inputPlaceholder: 'Escribe o graba un audio...',
                    sendButtonText: 'Enviar'
                  }
                }
              });
            }
          }}
        />
      </body>
    </html>
  );
}

