import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import "@n8n/chat/style.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {children}

        <Script
          id="n8n-chat-widget"
          strategy="afterInteractive"
          src="https://cdn.jsdelivr.net/npm/@n8n/chat/dist/chat.bundle.es.js"
          type="module"
          onLoad={() => {
            // @ts-ignore
            window.Chat.createChat({
              webhookUrl: 'TU_URL_DE_N8N_CHAT_TRIGGER', // Reemplaza por la URL de "Production" de tu Chat Trigger
              i18n: {
                en: {
                  title: 'Asistente de IA',
                  sendButtonText: 'Enviar',
                  inputPlaceholder: 'Escribe o graba un audio...',
                }
              }
            });
          }}
        />

      </body>
    </html>
  );
}

